### PR TITLE
added HBE Level 3 Tech test 1 to 5 answers

### PR DESCRIPTION
**Pull request by pankajsirari222**
added HBE Level 3 Tech test 1 to 5 answers

### CODE REVIEW

**Comment by tutoriex-tech** [comment]
How did you get those keys?

**Comment by pankajsirari222** [comment]
Telegram pe mil jaati hai

**Comment by pankajsirari222** [comment]
Level 4 ke solution bhi hai chahiye kya?

**Comment by tutoriex-tech** [comment]
Ok, so you didn't extract it from the answer key page.  No issue I'll merge the PR after verifying the keys myself. Next time create a different branch for PR.

**Comment by pankajsirari222** [comment]
Ok sure

**Review by tutoriex-tech — APPROVED** [review]

**Pull request merged**
